# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_0.1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 80, 300, 300))
        self.gridLayoutWidget.setMaximumSize(QtCore.QSize(300, 300))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.I6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I6_Button.setText("")
        self.I6_Button.setObjectName("I6_Button")
        self.gridLayout.addWidget(self.I6_Button, 9, 5, 1, 1)
        self.A7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A7_Button.setText("")
        self.A7_Button.setObjectName("A7_Button")
        self.gridLayout.addWidget(self.A7_Button, 1, 6, 1, 1)
        self.J7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J7_Button.setText("")
        self.A7_Button.clicked.connect(self.changecolor)

        self.J7_Button.setObjectName("J7_Button")
        self.gridLayout.addWidget(self.J7_Button, 10, 6, 1, 1)
        self.G9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G9_Button.setText("")
        self.G9_Button.setObjectName("G9_Button")
        self.gridLayout.addWidget(self.G9_Button, 7, 8, 1, 1)
        self.F10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F10_Button.setText("")
        self.F10_Button.setObjectName("F10_Button")
        self.gridLayout.addWidget(self.F10_Button, 6, 9, 1, 1)
        self.D4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D4_Button.setText("")
        self.D4_Button.setObjectName("D4_Button")
        self.gridLayout.addWidget(self.D4_Button, 4, 3, 1, 1)
        self.G6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G6_Button.setText("")
        self.G6_Button.setObjectName("G6_Button")
        self.gridLayout.addWidget(self.G6_Button, 7, 5, 1, 1)
        self.D10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D10_Button.setText("")
        self.D10_Button.setObjectName("D10_Button")
        self.gridLayout.addWidget(self.D10_Button, 4, 9, 1, 1)
        self.G1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G1_Button.setText("")
        self.G1_Button.setObjectName("G1_Button")
        self.gridLayout.addWidget(self.G1_Button, 7, 0, 1, 1)
        self.I3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I3_Button.setText("")
        self.I3_Button.setObjectName("I3_Button")
        self.gridLayout.addWidget(self.I3_Button, 9, 2, 1, 1)
        self.B1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B1_Button.setText("")
        self.B1_Button.setObjectName("B1_Button")
        self.gridLayout.addWidget(self.B1_Button, 2, 0, 1, 1)
        self.D5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D5_Button.setText("")
        self.D5_Button.setObjectName("D5_Button")
        self.gridLayout.addWidget(self.D5_Button, 4, 4, 1, 1)
        self.D7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D7_Button.setText("")
        self.D7_Button.setObjectName("D7_Button")
        self.gridLayout.addWidget(self.D7_Button, 4, 6, 1, 1)
        self.I1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I1_Button.setText("")
        self.I1_Button.setObjectName("I1_Button")
        self.gridLayout.addWidget(self.I1_Button, 9, 0, 1, 1)
        self.H6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H6_Button.setText("")
        self.H6_Button.setObjectName("H6_Button")
        self.gridLayout.addWidget(self.H6_Button, 8, 5, 1, 1)
        self.C2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C2_Button.setText("")
        self.C2_Button.setObjectName("C2_Button")
        self.gridLayout.addWidget(self.C2_Button, 3, 1, 1, 1)
        self.D3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D3_Button.setText("")
        self.D3_Button.setObjectName("D3_Button")
        self.gridLayout.addWidget(self.D3_Button, 4, 2, 1, 1)
        self.G8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G8_Button.setText("")
        self.G8_Button.setObjectName("G8_Button")
        self.gridLayout.addWidget(self.G8_Button, 7, 7, 1, 1)
        self.B5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B5_Button.setText("")
        self.B5_Button.setObjectName("B5_Button")
        self.gridLayout.addWidget(self.B5_Button, 2, 4, 1, 1)
        self.G4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G4_Button.setText("")
        self.G4_Button.setObjectName("G4_Button")
        self.gridLayout.addWidget(self.G4_Button, 7, 3, 1, 1)
        self.F1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F1_Button.setText("")
        self.F1_Button.setObjectName("F1_Button")
        self.gridLayout.addWidget(self.F1_Button, 6, 0, 1, 1)
        self.G3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G3_Button.setText("")
        self.G3_Button.setObjectName("G3_Button")
        self.gridLayout.addWidget(self.G3_Button, 7, 2, 1, 1)
        self.I8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I8_Button.setText("")
        self.I8_Button.setObjectName("I8_Button")
        self.gridLayout.addWidget(self.I8_Button, 9, 7, 1, 1)
        self.E6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E6_Button.setText("")
        self.E6_Button.setObjectName("E6_Button")
        self.gridLayout.addWidget(self.E6_Button, 5, 5, 1, 1)
        self.B3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B3_Button.setText("")
        self.B3_Button.setObjectName("B3_Button")
        self.gridLayout.addWidget(self.B3_Button, 2, 2, 1, 1)
        self.B6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B6_Button.setText("")
        self.B6_Button.setObjectName("B6_Button")
        self.gridLayout.addWidget(self.B6_Button, 2, 5, 1, 1)
        self.E1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E1_Button.setText("")
        self.E1_Button.setObjectName("E1_Button")
        self.gridLayout.addWidget(self.E1_Button, 5, 0, 1, 1)
        self.H2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H2_Button.setText("")
        self.H2_Button.setObjectName("H2_Button")
        self.gridLayout.addWidget(self.H2_Button, 8, 1, 1, 1)
        self.E8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E8_Button.setText("")
        self.E8_Button.setObjectName("E8_Button")
        self.gridLayout.addWidget(self.E8_Button, 5, 7, 1, 1)
        self.B4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B4_Button.setText("")
        self.B4_Button.setObjectName("B4_Button")
        self.gridLayout.addWidget(self.B4_Button, 2, 3, 1, 1)
        self.I4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I4_Button.setText("")
        self.I4_Button.setObjectName("I4_Button")
        self.gridLayout.addWidget(self.I4_Button, 9, 3, 1, 1)
        self.A9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A9_Button.setText("")
        self.A9_Button.setObjectName("A9_Button")
        self.gridLayout.addWidget(self.A9_Button, 1, 8, 1, 1)
        self.J9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J9_Button.setText("")
        self.J9_Button.setObjectName("J9_Button")
        self.gridLayout.addWidget(self.J9_Button, 10, 8, 1, 1)
        self.C8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C8_Button.setText("")
        self.C8_Button.setObjectName("C8_Button")
        self.gridLayout.addWidget(self.C8_Button, 3, 7, 1, 1)
        self.F6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C8_Button.clicked.connect(self.changecolor)

        self.F6_Button.setText("")
        self.F6_Button.setIconSize(QtCore.QSize(16, 16))
        self.F6_Button.setObjectName("F6_Button")
        self.gridLayout.addWidget(self.F6_Button, 6, 5, 1, 1)
        self.H4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H4_Button.setText("")
        self.H4_Button.setObjectName("H4_Button")
        self.gridLayout.addWidget(self.H4_Button, 8, 3, 1, 1)
        self.F3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F3_Button.setText("")
        self.F3_Button.setObjectName("F3_Button")
        self.gridLayout.addWidget(self.F3_Button, 6, 2, 1, 1)
        self.C6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C6_Button.setText("")
        self.C6_Button.setObjectName("C6_Button")
        self.gridLayout.addWidget(self.C6_Button, 3, 5, 1, 1)
        self.E4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C6_Button.clicked.connect(self.changecolor)

        self.E4_Button.setText("")
        self.E4_Button.setObjectName("E4_Button")
        self.gridLayout.addWidget(self.E4_Button, 5, 3, 1, 1)
        self.I2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I2_Button.setText("")
        self.I2_Button.setObjectName("I2_Button")
        self.gridLayout.addWidget(self.I2_Button, 9, 1, 1, 1)
        self.C3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C3_Button.setText("")
        self.C3_Button.setObjectName("C3_Button")
        self.gridLayout.addWidget(self.C3_Button, 3, 2, 1, 1)
        self.E3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E3_Button.setText("")
        self.E3_Button.setObjectName("E3_Button")
        self.gridLayout.addWidget(self.E3_Button, 5, 2, 1, 1)
        self.F5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F5_Button.setText("")
        self.F5_Button.setObjectName("F5_Button")
        self.gridLayout.addWidget(self.F5_Button, 6, 4, 1, 1)
        self.J5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J5_Button.setText("")
        self.J5_Button.setObjectName("J5_Button")
        self.gridLayout.addWidget(self.J5_Button, 10, 4, 1, 1)
        self.C4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C4_Button.setText("")
        self.C4_Button.setObjectName("C4_Button")
        self.gridLayout.addWidget(self.C4_Button, 3, 3, 1, 1)
        self.I5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I5_Button.setText("")
        self.I5_Button.setObjectName("I5_Button")
        self.gridLayout.addWidget(self.I5_Button, 9, 4, 1, 1)
        self.E5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E5_Button.setText("")
        self.E5_Button.setObjectName("E5_Button")
        self.gridLayout.addWidget(self.E5_Button, 5, 4, 1, 1)
        self.C1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C1_Button.setText("")
        self.C1_Button.setObjectName("C1_Button")
        self.gridLayout.addWidget(self.C1_Button, 3, 0, 1, 1)
        self.J10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J10_Button.setText("")
        self.J10_Button.setObjectName("J10_Button")
        self.gridLayout.addWidget(self.J10_Button, 10, 9, 1, 1)
        self.A6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A6_Button.setText("")
        self.A6_Button.setObjectName("A6_Button")
        self.gridLayout.addWidget(self.A6_Button, 1, 5, 1, 1)
        self.I10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I10_Button.setText("")
        self.I10_Button.setObjectName("I10_Button")
        self.gridLayout.addWidget(self.I10_Button, 9, 9, 1, 1)
        self.E9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E9_Button.setText("")
        self.E9_Button.setObjectName("E9_Button")
        self.gridLayout.addWidget(self.E9_Button, 5, 8, 1, 1)
        self.B10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B10_Button.setText("")
        self.B10_Button.setObjectName("B10_Button")
        self.gridLayout.addWidget(self.B10_Button, 2, 9, 1, 1)
        self.I9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I9_Button.setText("")
        self.I9_Button.setObjectName("I9_Button")
        self.gridLayout.addWidget(self.I9_Button, 9, 8, 1, 1)
        self.B2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B2_Button.setText("")
        self.B2_Button.setObjectName("B2_Button")
        self.gridLayout.addWidget(self.B2_Button, 2, 1, 1, 1)
        self.I7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.I7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.I7_Button.setText("")
        self.I7_Button.setObjectName("I7_Button")
        self.gridLayout.addWidget(self.I7_Button, 9, 6, 1, 1)
        self.E2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E2_Button.setText("")
        self.E2_Button.setObjectName("E2_Button")
        self.gridLayout.addWidget(self.E2_Button, 5, 1, 1, 1)
        self.D1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D1_Button.setText("")
        self.D1_Button.setObjectName("D1_Button")
        self.gridLayout.addWidget(self.D1_Button, 4, 0, 1, 1)
        self.D9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D9_Button.setText("")
        self.D9_Button.setObjectName("D9_Button")
        self.gridLayout.addWidget(self.D9_Button, 4, 8, 1, 1)
        self.E10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E10_Button.setText("")
        self.E10_Button.setObjectName("E10_Button")
        self.gridLayout.addWidget(self.E10_Button, 5, 9, 1, 1)
        self.H9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H9_Button.setText("")
        self.H9_Button.setObjectName("H9_Button")
        self.gridLayout.addWidget(self.H9_Button, 8, 8, 1, 1)
        self.C5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C5_Button.setText("")
        self.C5_Button.setObjectName("C5_Button")
        self.gridLayout.addWidget(self.C5_Button, 3, 4, 1, 1)
        self.H10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H10_Button.setText("")
        self.H10_Button.setObjectName("H10_Button")
        self.gridLayout.addWidget(self.H10_Button, 8, 9, 1, 1)
        self.B8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B8_Button.setText("")
        self.B8_Button.setObjectName("B8_Button")
        self.gridLayout.addWidget(self.B8_Button, 2, 7, 1, 1)
        self.J1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J1_Button.setText("")
        self.J1_Button.setObjectName("J1_Button")
        self.gridLayout.addWidget(self.J1_Button, 10, 0, 1, 1)
        self.A3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A3_Button.setText("")
        self.A3_Button.setObjectName("A3_Button")
        self.gridLayout.addWidget(self.A3_Button, 1, 2, 1, 1)
        self.J6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J6_Button.setText("")
        self.J6_Button.setObjectName("J6_Button")
        self.gridLayout.addWidget(self.J6_Button, 10, 5, 1, 1)
        self.F9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F9_Button.setText("")
        self.F9_Button.setObjectName("F9_Button")
        self.gridLayout.addWidget(self.F9_Button, 6, 8, 1, 1)
        self.H3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H3_Button.setText("")
        self.H3_Button.setObjectName("H3_Button")
        self.gridLayout.addWidget(self.H3_Button, 8, 2, 1, 1)
        self.B9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B9_Button.setText("")
        self.B9_Button.setObjectName("B9_Button")
        self.gridLayout.addWidget(self.B9_Button, 2, 8, 1, 1)
        self.J8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J8_Button.setText("")
        self.J8_Button.setObjectName("J8_Button")
        self.gridLayout.addWidget(self.J8_Button, 10, 7, 1, 1)
        self.A2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A2_Button.setText("")
        self.A2_Button.setObjectName("A2_Button")
        self.gridLayout.addWidget(self.A2_Button, 1, 1, 1, 1)
        self.F7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F7_Button.setText("")
        self.F7_Button.setObjectName("F7_Button")
        self.gridLayout.addWidget(self.F7_Button, 6, 6, 1, 1)
        self.E7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.E7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.E7_Button.setText("")
        self.E7_Button.setObjectName("E7_Button")
        self.gridLayout.addWidget(self.E7_Button, 5, 6, 1, 1)
        self.G5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G5_Button.setText("")
        self.G5_Button.setObjectName("G5_Button")
        self.gridLayout.addWidget(self.G5_Button, 7, 4, 1, 1)
        self.H1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H1_Button.setText("")
        self.H1_Button.setObjectName("H1_Button")
        self.gridLayout.addWidget(self.H1_Button, 8, 0, 1, 1)
        self.D6_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D6_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D6_Button.setText("")
        self.D6_Button.setObjectName("D6_Button")
        self.gridLayout.addWidget(self.D6_Button, 4, 5, 1, 1)
        self.H7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H7_Button.setText("")
        self.H7_Button.setObjectName("H7_Button")
        self.gridLayout.addWidget(self.H7_Button, 8, 6, 1, 1)
        self.C10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C10_Button.setText("")
        self.C10_Button.setObjectName("C10_Button")
        self.gridLayout.addWidget(self.C10_Button, 3, 9, 1, 1)
        self.D2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D2_Button.setText("")
        self.D2_Button.setObjectName("D2_Button")
        self.gridLayout.addWidget(self.D2_Button, 4, 1, 1, 1)
        self.J4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J4_Button.setText("")
        self.J4_Button.setObjectName("J4_Button")
        self.gridLayout.addWidget(self.J4_Button, 10, 3, 1, 1)
        self.B7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.B7_Button.setText("")
        self.B7_Button.setObjectName("B7_Button")
        self.gridLayout.addWidget(self.B7_Button, 2, 6, 1, 1)
        self.H5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H5_Button.setText("")
        self.B7_Button.clicked.connect(self.changecolor)

        self.H5_Button.setObjectName("H5_Button")
        self.gridLayout.addWidget(self.H5_Button, 8, 4, 1, 1)
        self.A5_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A5_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A5_Button.setText("")
        self.A5_Button.setObjectName("A5_Button")
        self.gridLayout.addWidget(self.A5_Button, 1, 4, 1, 1)
        self.J3_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J3_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J3_Button.setText("")
        self.J3_Button.setObjectName("J3_Button")
        self.gridLayout.addWidget(self.J3_Button, 10, 2, 1, 1)
        self.C9_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C9_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C9_Button.setText("")
        self.C9_Button.setObjectName("C9_Button")
        self.gridLayout.addWidget(self.C9_Button, 3, 8, 1, 1)
        self.F8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F8_Button.setText("")
        self.F8_Button.setObjectName("F8_Button")
        self.gridLayout.addWidget(self.F8_Button, 6, 7, 1, 1)
        self.G2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G2_Button.setText("")
        self.G2_Button.setObjectName("G2_Button")
        self.gridLayout.addWidget(self.G2_Button, 7, 1, 1, 1)
        self.F4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F4_Button.setText("")
        self.F4_Button.setObjectName("F4_Button")
        self.gridLayout.addWidget(self.F4_Button, 6, 3, 1, 1)
        self.D8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.D8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.D8_Button.setText("")
        self.D8_Button.setObjectName("D8_Button")
        self.gridLayout.addWidget(self.D8_Button, 4, 7, 1, 1)
        self.H8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.H8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.H8_Button.setText("")
        self.H8_Button.setObjectName("H8_Button")
        self.gridLayout.addWidget(self.H8_Button, 8, 7, 1, 1)
        self.A4_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A4_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A4_Button.setText("")
        self.A4_Button.setObjectName("A4_Button")
        self.gridLayout.addWidget(self.A4_Button, 1, 3, 1, 1)
        self.F2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.F2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.F2_Button.setText("")
        self.F2_Button.setObjectName("F2_Button")
        self.gridLayout.addWidget(self.F2_Button, 6, 1, 1, 1)
        self.A10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A10_Button.setText("")
        self.A10_Button.setObjectName("A10_Button")
        self.gridLayout.addWidget(self.A10_Button, 1, 9, 1, 1)
        self.J2_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.J2_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.J2_Button.setText("")
        self.J2_Button.setObjectName("J2_Button")
        self.gridLayout.addWidget(self.J2_Button, 10, 1, 1, 1)
        self.A8_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A8_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A8_Button.setText("")
        self.A8_Button.setObjectName("A8_Button")
        self.gridLayout.addWidget(self.A8_Button, 1, 7, 1, 1)
        self.G10_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G10_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G10_Button.setText("")
        self.G10_Button.setObjectName("G10_Button")
        self.gridLayout.addWidget(self.G10_Button, 7, 9, 1, 1)
        self.C7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.C7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.C7_Button.setText("")
        self.C7_Button.setObjectName("C7_Button")
        self.gridLayout.addWidget(self.C7_Button, 3, 6, 1, 1)
        self.G7_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.G7_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.G7_Button.setText("")
        self.C7_Button.clicked.connect(self.changecolor)

        self.G7_Button.setObjectName("G7_Button")
        self.gridLayout.addWidget(self.G7_Button, 7, 6, 1, 1)
        self.A1_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A1_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.A1_Button.setText("")
        self.A1_Button.setObjectName("A1_Button")
        self.gridLayout.addWidget(self.A1_Button, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def changecolor(self):
        self.A7_Button.setStyleSheet("background-color: red" )
        self.B7_Button.setStyleSheet("background-color: red" )
        self.C7_Button.setStyleSheet("background-color: red" )
        self.C6_Button.setStyleSheet("background-color: red" )
        self.C8_Button.setStyleSheet("background-color: red" )

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
